version: "3.1"
services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - .:/application
      - ./compose/nginx/default.conf:/etc/nginx/conf.d/default.conf

  converter:
    build: compose/converter
    container_name: time_converter
    working_dir: /application
    volumes:
      - .:/application